#!/usr/bin/env python3
"""Embed the authenticated finite rotary table in the research-only Swift path."""
import argparse
import base64
import hashlib
from pathlib import Path

SHA256 = '8914caa7d89a1f8a0038fc6c74933c46a3d56424767d3c30057dd4f5e61431b7'


def render(path):
    with path.open('rb') as source:
        raw = source.read(2054 * 2 * 32 * 4 + 1)
    if len(raw) != 2054 * 2 * 32 * 4 or hashlib.sha256(raw).hexdigest() != SHA256:
        raise ValueError('not the authenticated bounded rotary table')
    encoded = base64.b64encode(raw).decode('ascii')
    text = '\n'.join('        ' + encoded[i:i + 120] for i in range(0, len(encoded), 120))
    return '''// Generated by Tools/vq_rotary_table_source.py. Do not edit the encoded table.
import CryptoKit
import Foundation
import MLX

/// Research-only finite FP32 reference table for positions 0..<2054. This is
/// the unchanged pinned Python GPU output, not a host/GPU transcendental
/// approximation. Both duplicated rotary halves are reconstructed exactly.
/// The 525,824-byte payload stays in the executable so frozen diagnostics do
/// not acquire a mutable resource dependency. Larger contexts need a separate
/// admitted table and qualification; this is not a production context limit.
package enum VQRotaryTable {
    package static let rows = 2054
    package static func supports(_ positions: [Int32]) -> Bool {
        !positions.isEmpty && positions.count <= rows
            && positions.allSatisfy { $0 >= 0 && $0 < Int32(rows) }
    }

    private static let values: MLXArray = {
        let data = Data(base64Encoded: encoded, options: .ignoreUnknownCharacters)!
        precondition(data.count == rows * 2 * 32 * 4)
        precondition(SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
            == "''' + SHA256 + '''")
        let words: [UInt32] = data.withUnsafeBytes { raw in
            (0..<(data.count / 4)).map { UInt32(littleEndian: raw.loadUnaligned(fromByteOffset: $0 * 4, as: UInt32.self)) }
        }
        let array = MLXArray(words, [rows, 2, 32]).view(dtype: .float32)
        eval(array)
        return array
    }()

    package static func angles(_ positions: MLXArray) -> (MLXArray, MLXArray) {
        precondition(positions.ndim == 2 && positions.dtype == .int32)
        precondition(supports(positions.reshaped([-1]).asArray(Int32.self)),
                     "VQ research rotary positions exceed the authenticated table")
        let cosine = values[0..., 0, 0...][positions]
        let sine = values[0..., 1, 0...][positions]
        return (concatenated([cosine, cosine], axis: -1), concatenated([sine, sine], axis: -1))
    }

    private static let encoded = """
''' + text + '''
        """
}
'''


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--table', required=True, type=Path)
    parser.add_argument('--output', required=True, type=Path)
    options = parser.parse_args()
    options.output.write_text(render(options.table))
